### ISSUE TITLE
Problem when installing clip-retrieval

### ISSUE THREAD

**Issue by DavisMeee** [MedARC-AI/fMRI-reconstruction-NSD#30]
Congrats for your paper accept!
I found out this when I was installing clip-retrieval package.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
clip-retrieval 2.37.0 requires torch<2,>=1.7.1, but you have torch 2.0.1 which is incompatible.

I think these may incompatible, how did you guys solve this problem out?

**Comment by PaulScotti** [comment]
Yes there are unfortunate dependency issues when it comes to installing everything. To get around it see our setup.sh file that separately installs packages sequentially. In our testing it was apparent that even though clip-retrieval says it requires torch<2, it actually works just fine with torch=2
