### ISSUE TITLE
Missing pretrain models in 'train_autoencoder.py'

### ISSUE THREAD

**Issue by DavisMeee** [MedARC-AI/fMRI-reconstruction-NSD#32]
I think there's a missing file for training autoencoder. (No released link for this pretrain model)
![image](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/61048672/d1e3031b-ad80-4160-b70b-622b3997ee23)

**Comment by Atom-101** [comment]
The weights for sd_image_var_autoenc.pth have been added to the HF repo. Check the updated README. Thanks.
