### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by DavisMeee** [MedARC-AI/fMRI-reconstruction-NSD#33]
Dear Paul,

I would like to know how you extract the data during the preprocessing stage. If it is convenient, would you like to provide a simple example program for reference?

Best,

**Comment by PaulScotti** [comment]
We used the outputs from GLMSingle provided by the NSD authors and then made our own webdatasets (similar to the following code):

https://github.com/MedARC-AI/fMRI-Algonauts-Challenge-2023/blob/main/src/algo_webdataset_creation.ipynb

**Comment by DavisMeee** [comment]
Dear Paul,

Thank you for your reply, but there's still a small question about the code. I noticed there's a normalization step when extracting brain signals from your own webdatasets. So I'm wondering if the data has been normalized in this work.

![image](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/61048672/5463a65d-f6b1-4538-84eb-786b9c188a97)

Best,

**Comment by PaulScotti** [comment]
Yes all betas are session-wise z-scored

**Comment by littlepure2333** [comment]
@PaulScotti , Hi Paul, thanks for sharing the code. But I still have some questions:
I am trying to make webdatasets for the rest 4 subjects (3,4,6,8). While using the code, I can not find several files in the original NSD dataset:
```
lh_file = f"/fsx/proj-medarc/fmri/natural-scenes-dataset/algonauts_data/dataset/{subject}/roi_masks/lh.all-vertices_fsaverage_space.npy"

rh_file = f"/fsx/proj-medarc/fmri/natural-scenes-dataset/algonauts_data/dataset/{subject}/roi_masks/rh.all-vertices_fsaverage_space.npy"

indices_path = "/fsx/proj-medarc/fmri/natural-scenes-dataset/COCO_73k_subj_indices.hdf5"

betas_nsd_mean = np.load(f"/fsx/proj-medarc/fmri/natural-scenes-dataset/challenge_scalars/challenge_mean_sess{sess}_{subj}.npy")

betas_nsd_std = np.load(f"/fsx/proj-medarc/fmri/natural-scenes-dataset/challenge_scalars/challenge_std_sess{sess}_{subj}.npy")
```

Could you please hint me where these files are? Or do you have the webdatasets of the rest subjects?
Really appreciate your kindness and effort❤️

**Comment by Zoe-Wan** [comment]
I think the mask data can be download from [**the algonauts 2023 data**](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSehZkqZOUNk18uTjRTuLj7UYmRGz-OkdsU25AyO3Wm6iAb0VA%2Fviewform%3Fusp%3Dsf_link), you can download it after filling a short table

**Comment by Zoe-Wan** [comment]
@PaulScotti 
Hi! I find the subject01's mask used in code 
https://github.com/MedARC-AI/fMRI-Algonauts-Challenge-2023/blob/main/src/algo_webdataset_creation.ipynb
has size 39548, so the subject01's voxel size is 39548. But in this experiment the size is 15724.

Are these two experiment using the same preprocess pipeline? Did I miss something?
And btw, I wonder if I can get the 3d voxel [N, 81, 104, 83](like the code in [src/models.py:214](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/blob/4d02ab3b63e45bb4e35c15f5d433a1ad0569ee77/src/models.py#L214)), not a flattened one, where can I get nsd data like that?

**Comment by Zoe-Wan** [comment]
I have found the roi data you used! I mistakenly thought you got the data with the script in the link, but the data actually comes from https://natural-scenes-dataset.s3.amazonaws.com/nsddata/ppdata/subj01/func1pt8mm/roi/nsdgeneral.nii.gz .
