### ISSUE TITLE
Some results becoming gray

### ISSUE THREAD

**Issue by Maxwells-Demons** [MedARC-AI/fMRI-reconstruction-NSD#40]
Hi! Thanks for your wonderful project! 
But I encountered a problem: After I retraining MindEye, I set recons_per_sample=4 to reconstruct images. And some of the results are becoming gray:
![rua_80](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/54426652/f4e581a2-1a4b-45cd-b733-80f4648870dd)
![rua_12](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/54426652/ff35421a-19af-4e06-a71b-28db33bd1773)
![rua_55](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/54426652/117f8d85-7f40-4700-8f25-9a0c338a43be)
However, it didn't happen when I use the released weights in huggingface. Do you have any idea about this? Whether I made mistakes in training or reconstruction settings?

**Comment by PaulScotti** [comment]
Yeah I think it's due to image augmentation being set to True during model training (we had it False for the paper's results, but the codebase here has it set to True accidentally, I should revise this...)
