### ISSUE TITLE
change batch size based on number of devices if using multi-gpu

### ISSUE THREAD

**Issue by song-wensong** [MedARC-AI/fMRI-reconstruction-NSD#43]
https://github.com/MedARC-AI/fMRI-reconstruction-NSD/blob/main/src/Train_MindEye.py#L189
Hello, why did you comment `batch_size *= accelerator.num_processes`?
If I use multi-GPU, don't I need `batch_size *= accelerator.num_processes`?

**Comment by PaulScotti** [comment]
I'm not sure, we never got multi-gpu working better than single-gpu so can't offer advice on multi-gpu implementations
