### ISSUE TITLE
What is `coco` in the dataloader

### ISSUE THREAD

**Issue by Boltzmachine** [MedARC-AI/fMRI-reconstruction-NSD#49]
https://github.com/MedARC-AI/fMRI-reconstruction-NSD/blob/6b30ea53c0f98b0a79b8f6828b6787a5913fd08d/src/Train_MindEye.py#L585

What is `coco` here?

**Comment by PaulScotti** [comment]
coco stands for the image's COCO73K ID, see the NSD data manual for more information: https://cvnlab.slite.page/p/NKalgWd__F/Untitled#e616ae2c

Also note we have a new MindEye2 repo which may be more useful if you are looking into this: https://github.com/MedARC-AI/MindEyeV2/tree/main
