### ISSUE TITLE
a question about versatile diffusion

### ISSUE THREAD

**Issue by songqianyi01** [MedARC-AI/fMRI-reconstruction-NSD#50]
![Snipaste_2024-07-10_18-00-47](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/144104622/ef8f8fcf-049a-4fa0-a456-42cb81eb7c1b)
Hello, can you tell me the structure of this folder vd_cache_dir? I can't access huggingface from the server. I hope you can tell me the file under this folder so that I can download it manually and put it in

**Comment by PaulScotti** [comment]
vd_cache_dir is just where the data gets downloaded when you use diffusers to download the pretrained Versatile Diffusion model: https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/versatile_diffusion

Try locally importing + downloading the pipeline and then you'll have the folder you can use to copy into your internet-restricted cluster.

Also note that this repository is now outdated, we recently released MindEye2 which improves upon MindEye1: https://github.com/MedARC-AI/MindEyeV2
