### ISSUE TITLE
A questions about coco data

### ISSUE THREAD

**Issue by songqianyi01** [MedARC-AI/fMRI-reconstruction-NSD#54]
Hello, I have been trying to align fmri to coco's text annotations with mindeye1 recently, so I would like to know where can I find the text annotations corresponding to cocoid's index in this picture in the data set divided by mindeye1? Do you have a hugging face page with the corresponding text annotations processed?
<img width="301" alt="Snipaste_2024-08-31_15-51-56" src="https://github.com/user-attachments/assets/52f7fe62-c31a-4523-bf39-ce2f506dbcf2">

<img width="219" alt="Snipaste_2024-08-31_15-48-56" src="https://github.com/user-attachments/assets/6b0ce8f5-b805-496f-a958-5fe407131330">

**Comment by PaulScotti** [comment]
https://huggingface.co/datasets/pscotti/naturalscenesdataset/tree/main

COCO_73k_annots.npy contains the text annotations, the curated one contains the curated version of it as talked about in the paper
